name: Go

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
      with: 
        working-directory: ./hello


