name: Lint go files

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
      with: 
        working-directory: ./hello


